---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: test
  secretRef:
    name: flux-system
  url: https://gitlab.com/magnit-online-services/devops/k8s-mgmt/yc-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
